FROM centos

RUN yum -y install httpd unzip
ENV HTML project-html-website
LABEL maintainer = Jason
LABEL vendor = JS SOFT TECH
LABEL random = yay
WORKDIR /var/www/html
ADD https://github.com/microsoft/$HTML/archive/master.zip ./code.zip
RUN useradd jason && chown jason:jason /var/www/html -R
RUN unzip code.zip && mv ./$HTML-master/* . && echo $HTML > ./env.html
USER jason
RUN rm -rf code.zip
USER root
COPY cmd.sh /cmd.sh
RUN chmod +x /cmd.sh
CMD /cmd.sh
