FROM centos
ARG user
RUN yum -y install httpd unzip
ENV HTML project-html-website
LABEL maintainer = Jason
LABEL vendor = JS SOFT TECH
LABEL random = yay
WORKDIR /var/www/html
ADD https://github.com/microsoft/$HTML/archive/master.zip ./code.zip
RUN unzip code.zip && mv ./$HTML-master/* . && echo $HTML > ./env.html
RUN useradd $user && chown $user:$user /var/www/html -R
USER $user
RUN rm -rf code.zip
USER root
CMD apachectl -DFOREGROUND
